### PR TITLE
Include the demos/ branches in sharplab

### PR DESCRIPTION
**Pull request by agocke**
These are preview branches that test out prototypes that aren't even at feature quality yet, more to get feedback on a design or idea

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks for submitting! How often are those created/deleted?
(Currently I don't have any automatic cleanup for deleted branches, 2-3 per month would be OK to clean manually e.g. once a year, but if it's 1 per day then it wouldn't work).

**Comment by agocke** [comment]
Probably one every few months. Even rarer than feature branches

**Comment by ashmind** [comment]
Sounds good!

**Comment by agocke** [comment]
Thank you!

**Pull request merged**
