### PR TITLE
Update defaults.ts to match C# convention

### PR DESCRIPTION
**Pull request by Youssef1313**

### CODE REVIEW

**Comment by ashmind** [comment]
Thanks! Unfortunately, I personally prefer the current style.
I know that output is inconsistent with it, and I have #90 to sort it out.

I might provide `.editorconfig` support in the future though.

**Comment by Youssef1313** [comment]
> I personally prefer the current style.

IMHO, it's not about personal preference, it's about **consistency** and using the **most popular** coding style known for C#.

**Comment by ashmind** [comment]
Why is it not about my personal preference? You say IMHO, so you already see it's subjective. If it was a work project it would be a team decision, but here there is no team, so I get to choose the style.

I do get it's annoying to adjust if you want to share with a different formatting, but then I use SharpLab as well and I'll have adjust other way around. I think best answer to that would be making it configurable in the future.

Btw K&R being less used might actually be good for learning -- Allman is popular because it is VS default, so maybe seeing K&R will make people consider it as a valid option.

**Comment by Youssef1313** [comment]
> Why is it not about my personal preference?

What I mean is to keep personal preference away when there is a **known** convention.

For example, personally, when I write in Java, I use K&R style. But when I write in C#, I use All-man style.

I like all-man style much more than K&R, but my personal opinion doesn't affect me when I write in Java.

**Comment by svick** [comment]
@Youssef1313 

> All-man style

FYI, it's [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), not All-man style. It's named after early C programmer, Eric Allman. It doesn't mean all men should use this style. 🙂

**Comment by Youssef1313** [comment]
> 
> 
> @Youssef1313
> 
> > All-man style
> 
> FYI, it's [Allman style](https://en.wikipedia.org/wiki/Indentation_style#Allman_style), not All-man style. It's named after early C programmer, Eric Allman. It doesn't mean all men should use this style. 🙂

Good to know the origin of the name :)
+ Thanks for the correction

**Pull request closed without merging**
