### PR TITLE
Full support for IL compilation (based on @kkokosa work)

### PR DESCRIPTION
**Pull request by ashmind**
This PR is to track the full IL support -- some further work to be done, so not ready to get merged yet.

### Before merge
- [x] Preparation (submodules)
- [x] Server adjustments and test fixes
- [x] WebApp adjustments and test fixes
- [x] Ensure execution fallback is not allowed for IL
- [x] New tests (server-side)
- [x] Proper code highlighting
- [x] Performance/memory optimizations

### After merge (on Edge)

- [ ] Check user experience in .NET Framework (will do on edge site)
- [ ] Stretch-goal: Proper value detection in debug mode

### Out-of-scope / Later

- Move more things to MirrorSharp
- Understand how assembly references are handled (raises warnings, but can wait)

### CODE REVIEW

**Comment by ashmind** [comment]
@kkokosa I'll track the progress of IL work in this PR, so that it's more visible

**Comment by ashmind** [comment]
Add task list to the description

**Comment by kkokosa** [comment]
Regarding to "Performance/memory optimizations" this will be an ongoing task on `Mobius.ILasm` side too.

**Comment by ashmind** [comment]
I changed some minor things in Mobius as well, see https://github.com/ashmind/Mobius.ILasm/commits/main.
Planning to PR it back to upstream at some point and then change back to NuGet from a submodule.

**Comment by ashmind** [comment]
Current state looks OK!

I'll merge it today and it will get deployed to the test site.
But I'll need to test a few more things before releasing to main site, so general availability won't be earlier than tomorrow.

**Comment by kkokosa** [comment]
Can't wait to see it live!

**Comment by am11** [comment]
It's live! Thanks a lot for this feature @kkokosa and @ashmind. 🎉
btw, `IL -> JIT ASM` is [currently broken](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AbEBLDaAuIAhgM4C2APgHRgakkAEADlNgG5H4wNECu+EHgDsS2BgHIAPAFkIAE14YYAPnEBYAFABvTQF8GAegMMYQuQwgAzBrXoMZ8xSs2aadEoxbtO3PgOGiPMAk+FBEYPgMJDBESubAMJbQidgwGHLYQtiRUgAKUBAA5mFkygAk6hoM1SYIXGaMANoAygCeITBkVPneXFQAwskAMtjAALptHV0A8sAAVjARmjpVNTS8IRBkDJkhREJg3GwQ2OYt7VxdPRx9g7Aj45OXVABKvEL42GQwA1tMuDAoM1AWxsIcSL8yP8lFAAOKmQE+OQAQXwoVG/BgIBANAEUAAFABKBgAXgY+M0NSpDAADABGWk0xmMyk1Qms6pGBjSGD4AAW8hIHIYVG+/PkzFYN24fNOMGA7WwhSi+E4YIYwqpx1OEhkREy5XE5M11OqIVYQkKjTGPCghSFq1NxIAAgBmDWOhgrU2c4w88XxGCFXY8SIvABqyNpCAATDSAKw0k2+hiDOTcUQAL24KAA7OSabHLOzPVTnfGGHTkwxnShq1QMBAwLFGJlssbSz7GjSbbYPAxzlNulKfL97qMJhdOlQAJLTKg8sjQVrNUIxbZMGCr2BEMjVkvVmdDAD6NLPNJADHS5oYACIACrhgCOAEVkcjpO/3wBRL/IowABzvkMhR/mBb5gZBUHQTBsHIqBf4oJYvCFCgqLIkIAByM7AIUABC97SDSfLhrCfJMGArR4QA7mAZAAJwHGQABi+AzrCmF8sAZDxmwcj9Hh2AAFrNHhrRyAA6ighREFJhQvN+9H3uxdJsEJsIAKq8AAIi+NIANIAFIwXhL4vBB97It+/TIgAEtg0hDLCv4wdMX7YN+QzIi+JBfhB742VBwDYDOf4Ie+/nvnhYVgQh0UwS50F4eF74pX+n4vjOGlRV+8V/oliVgXlcHIsl2BRZZJVVXBhXUdV9UNY1UGhQF9X9IFVlpTB/SJkJAAafI0n+KItalf7Fcio1tV+sLIrwdHhiQwAxp+751X+kWTX+s2NXleEdU1h1HdVpkzl1nV/oF2UaR10j4blx2PU9UHfoZ97NAA1jO8WFVF/l4X1snxh9wCunImYaUI4a8HIsIYPgInIggQxzJtpl4UNX74JdmEANRfhA3nviiX79Jh95yLZhlMNx4NgYZ1F5VNM50uGln6S+eWRTONJyOGzQaf5/RDRBzE4/0wCwvR5UwaNzG2UTyL9JF2lIG9n7MeFkWFQd8F/lNE2bZNdUTe+s14b+/TnUbRPxcxeX0VZaGmaVP5QZ+8l8kJ76E4rYHUdpsL9BJQ0udp4F4ZYsV4WQ77NF+2kGMiuRAQYAdJ61+Voe+ifJ6n6dQdFumwdpCCYctLx0pLGn48xmHxmArovBgwCc5hkkIDSsmcY3ClCRJCAYEJMbMTSQmc7CoPQ+po+yfRvBDGYNNkHSH3IrCdKZgAmjG9GtJLGDld+mFsMAfV4SQ/XN0J358lxZAvJffWhS8DFVw/fKwxgp+gbwW9N2wMA+E2BbyhBgf+b5gASXDF3KWa9vwYBhgxKA48vytCgrkeisJ8DhnwABe8KAXjTEKK6Wycghh0nwEwOY0klZDDkEgPqzEt5CUwtMfohk8Lxxsi8aiW9kToPfNlGWcFmIoBEVtZ641MrnSqpHF8u9WgvFhAgEg94JLMRpvhfAYAYwnwWhgIYD8lpQQMK0bKM5fpSOsTY2xdj7EOMcU45xLjXFuPcR4zxkEDrrVKtRO6XjAlBOCSE0JYTwkRMiVE6JMTYl/hJLeQ8J5zzxkvM2DAGAVQWmVHkAoxRdyGmxFIPUBoyjKEKMeY8eFSAwFQNpRY8gYAUBpMeOk4h8TmkyIUEsPoGBHlPGeIgl5nR0hpJ0y0PSfT9PPJYS86QwBUGwCgKgSZOzVGmfSC8DAhAwGokQKAUABxPGnNcUcdwYAPEnEOMSXAkkDLpKk7ZuyIDzB2CIVUBwjgnDOMcq4I5bjDAnL82c85FzLm3OubEuJoD4l4JkPB1pJmmg2XSIZKpGwLNWb0qgoRWjVm9L0moKLQBXjkBilZ1YqQorAGk2ImTxk5MkPkIoJRCkgGKdIfUQhyjlMqbCZpp52l9iaMC05ALxyPCnF0OcVAIW7iRYSjZMY6SXiYBAJglKiXJJpDGGMcyYhsB+IwJVMBqz6C5KYcwOKoB4rWQwSwmQ6W2t6QSwlhhjDRCfLwUwhxmAnA+JeWUch0xCE1es7VMYUBzLJU2CldqqURsecAKAlgWxGr6RGuQLh41aoGTGXM0byVYrdRmvNAFaUZNBFASIuwPm+u1D8qVw5eg/HOZc4FM5tLYBIGqkgRBgBKGxF2ntEBohEmzSW91UQYBep9dwNV8LA2nBDWG0tZ4YxyEvJah1QgnVmqnZahgfJ9hksBBOn0XJPXes+X6xdR7l2mDueurEDBYD4GFOa4wh6rAMDFAKcwuSWUFIqEUkp3KKjnuqKKXk/6eAeE6AO1o970wKlEMqPYnwwAel6Qy3UYGeUVOPPylpNIjQUhzdUYVRym1itbYCyVQ4ZVyu2A6XpLp3TClddSLk/pYMJGDCIUMDAIxRkLHGeiYBqxcjTBmbA2YGD5nxIWXMCqywVgApB6kGyzzRv2YUONvTtMqpsHSqtNb3n7F9bhwczxaNjguUCptswFgRGxPeCA24unjrtdppAl430foPWYCw1g/0SkA/k0oIH2WSHw2UwjxHBWaegwGOD0QyCIeQ/KRU6HVSYewz6XDHKuUEcqdU6IdSGnpgFW0jsk7cPABqagb8BxGlyG0pwIg+4awcc9FxqkPGYMSn4yGTgwnIzRjjEQOsdrpONKiHJ7gdJ6IFgQHSV0qmajlgYDGesGKWxvPbORyd3YbRwo+ABa0DBGsVZQC1yA6Y5A3JgKxn0B4fPap06SvTBmpmfeM+kzJ52EU2hsyc/5dGJVXOeIMIQhrq3YmYgUMg5XakoE85aDp6IJlPrPH59Fsbi3Is+wWkzGSbDuBFTRiH9n21NvvDAOoVB7vyC6dRocdm22OaHAzpnLOMiWmxIUXkx4NL3mYgBbzhnPs0tJUW3HvMK3f2wNWt5ewb3WdFTTrnDHni8/wMz1rAvCjYnhPgDHhRYXwsu2MTb4b7l6tfbyQLFrgs/rCwBpleTWXReK6U3lVSmsoHqQ9ppLS2nZs/SYN31gqNe6A1F7NQA==):
```
System.BadImageFormatException: Could not load file or assembly '<Unknown>'. Index not found. (0x80131124)

File name: '<Unknown>'

   at System.Runtime.Loader.AssemblyLoadContext.InternalLoad(ReadOnlySpan`1 arrAssembly, ReadOnlySpan`1 arrSymbols)

   at System.Runtime.Loader.AssemblyLoadContext.LoadFromStream(Stream assembly, Stream assemblySymbols)

   at SharpLab.Server.Decompilation.JitAsmDecompiler.Decompile(CompilationStreamPair streams, TextWriter codeWriter) in D:\a\SharpLab\SharpLab\source\Server\Decompilation\JitAsmDecompiler.cs:line 37

   at SharpLab.Server.MirrorSharp.SlowUpdate.WriteResult(IFastJsonWriter writer, Object result, IWorkSession session) in D:\a\SharpLab\SharpLab\source\Server\MirrorSharp\SlowUpdate.cs:line 181

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.SendSlowUpdateAsync(IReadOnlyList`1 diagnostics, WorkSession session, Object extensionResult, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 72

   at MirrorSharp.Internal.Handlers.SlowUpdateHandler.ExecuteAsync(AsyncData data, WorkSession session, ICommandResultSender sender, CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Handlers\SlowUpdateHandler.cs:line 40

   at MirrorSharp.Internal.Connection.ReceiveAndProcessInternalAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 112

   at MirrorSharp.Internal.Connection.ReceiveAndProcessAsync(CancellationToken cancellationToken) in D:\a\SharpLab\SharpLab\source\#external\mirrorsharp\Common\Internal\Connection.cs:line 67
```

**Comment by ashmind** [comment]
@am11 Thanks for raising this -- it's not quite broken, but needs `.assembly` command: https://sharplab.io/#v2:DYLglsA0AuIIYGcC2AfAAgNgAQEEsG8BYAKAF8SSA6AY2EQSwAcAnMANzmgFMs4BXaAHteAOwRgsAcgA8AWUEATPsC4A+SSSJksAeh1YuIhVkEAzLLXpY5i5WorEadBAxbtOPfkNHjeAIwRoZjhqaCwELjgVYz8uU0FmOLAuYAUwETAwmQAFZkEAc2CkVQASDWIsSoMAD24jBgBtAGUAT0CuJEpc925KAGEErgAZMD8AXVb2zoB5PwArLlDNEiqsGj5AwSQsdMC4EWoeNkEwY2a27k7ujl6BxJHxycvKACU+EWgwJC5+rcYILjMJqAthgQ4IX5If4qZgAcUMgI8Chw0CCowEXBAIBoQmYAAoAJRYAC8WDxK1WVQADABGLBUqn0xkMimVAms3T6WRcaAAC0UCA5lG+fMUTFYNx4vNOXD8bTA+XC0E4YKwHNWx1OUjkcHSpUkZPVlMqgVYInyDTGvGY+UFFWNWCJaAAzGr7ZUtA7OVhuaKYlx8rteGEXgA1PBU6oAJipAFYqUbKnosAMFDxxAAvHgAFgA7GTI1HTOz3ZS0LGsDTE1g0Nnq5RgIJqFEGOlMobS16GlSrZYXFhzlMuhKPL97qMJhcOpQAJLTSjcpAJFpNIKRbaMLirxJwJDVkvVmdDAD6DIZICwqVNWAARAAVUMARwAijgcLI32+AKKfnB6AAcb5DPkv6ga+oEQZBUHQTBOAgb+2amHw+TZiiOAiAAcjOfj5AAQneshUryoawryjDUC0uEAO7UEgACcBxIAAYtAM6whhvJ+EgsZsAofS4WAABaTS4S0CgAOrZvkcCSfkLxfnRd5sTSbCCbCACqfAACLPlSADSABS0G4c+LzgXeOBfn0OAABJgLIQywj+0HTJ+YBfkMODPggn7gW+1mQX4YAzr+8Fvn5b64aFoHwVF0HOVBuFhW+yW/h+z4zupkWfnFv4JQloG5bBOBJWAkUWcVlWwQVVFVXV9UNZBIX+XVfQBZZqXQX08aCQAGryVK/sizUpb+RU4CNrWfrCOB8LRoYIH4UYfm+tW/hFE2/jNDW5bh7WNQdh1VSZM6dR1v4BVl6ntbIeE5UdD2PZBX4GXeTQANYznFBWRX5uG9TJsbvX4zoKBm6kiKGfAKLCwDQMJODVEMcwbSZuGDZ+0AXRhADUn6CF5b7Ip+fQYXeCg2QZjBcWDoEGVRuWTTONKhhZenPrlEUzlSCihk06l+X0g3gUx2N9H4sJ0WV0EjUxNmEzgfQRVpGCvR+TFhRFBX7XBv6TeNG0TbV41vjNuE/n0Z2G4TcVMbldGWahJkld+kEfnJvKCW+BMK6BVFabCfTiYNzlaWBuGmDFuFIG+TSflpOg4NkgE6P7ictXlqFvgnScp2nkFRTpMFadUGFLS8NIS+peNMRhsbUM6LzAH4HMYRJ1RUjJHEN/JgnidUwCCVGTFUoJHOwiDUNqSPMl0XwQxGNTSA0u9OCwjSGYAJpRnRLQS8AZVfhhbB+L1uEIH1TeCV+vKcUgLwX71IUvPRlf37yMPACfIF8JvjdsNQPCbBN5QmAH/V8fhxKhk7pLVeX5gDQ3oswMen4WiQWyHRWE0BQzQH/HebMLxpj5GdDZBQQwaTQEYHMKSishgKAwL1Jim9BIYWmH0AyuE47WReFRTeOA0FviytLWCTFszCM2k9MaGUzqVQjs+HeLQXiwmqAgO84kmLUzwtAagUZj7zWAEMe+i1II6BaFlGcP1JFWOsTY2xdj7EOMcU45xLjXFuPcR4iC+01olSordTxATAlBOCSE0JYTwkRMiVE6JMTfzEhvIeE8Z5YwXmbMAYASozSKhyHkQou59RYhkDqPUJRVD5GPMeXCiAuAYGzFpRYiguAoCpMeGkkg8SmnSPkEsXojyngZHAC8aAaRUk6eaHpDo+lnlMBeVI1BKBgGzJQBMnYqhTNpFSC8IguBUTgMwZgA4njTmuKOO4wwJxHM6KJbgiT+k0hSVgbZVFBDzB2GIZUBwjgnDOJc4cPQfhnIeJOIcc4FwdGXNudcWIcQJDxHwdIuDLQTONOsmkgylSNnmSsr0lAggtGrJ6L0aykm0j8LMhQmLlnVlWKi6gqSogZLGdk6QuQChFAKSAIpshdQiFKGUipsJmmnnaX2RovyTm3EGEC35oLIW7mRUS9ZUYaQXkYIIRg1LiX9KjFGWZkQ2A/AYEqrg1ZSDekMMYXFzB8WrMqKYdIDKbVekJUS70ERHx8EMIcJgJwPgXmlAoNMIhNWVCVdmcllLsWuqwEqh5fhmCmBbIamNJKowKAcNGlN2rcwRqbFS21lIlX/npek0EzAwi7A+d6zUPypxXBHJK8cjw62zi0mABAaqEBwD8CoLEbaO2CAiISDN0bkzus9Z8n1CL/WnCDSGrNDI00XgtfakQjrTXmqMFgXk+wKWAhHcaMdXAPVep4Gq6d27Z2GFuYuzEWBEjQA5Ga5MFqTDmBFPyYwOS2X5LKIU4pvKygHrWB+sU9AOg9paJetMcpxCKj2J8agbovRMu1ABvl5TjyCpaVSA05IC2rFFYcltEqAVSouS22Va5dzhH3DWV0HIXWUmTL6T9WBYiBjEMGLAYYIzRipHRag1ZkypnTGALMWB8x4kjLmBVqxyxYH/MBmlJLzyXgUHs/I+bemqZVRYBlZaK3vP2N61Dg5nikbHOc5tQ5ZgLFCFiO8ghtxdOHQW9ZVIMAXgfU+zdxgzBYFA1+lluT2V/s5dIdDpTMPYeFcB4UPI2PgaQJB6Dsp5TweVIh5DDpUNcp5RhipVSIi1PqdQRpQq2kdkzahvw1TalfgOI0hQWlOBwDoy6HLHphNckS2KDjQZOA8fDPSfjcA6wFpE408I4meA0jogWaoNJnRyaqApqM9ZMUtjee2fDmbuxWnhR8f8lp2P1ezI18raYFDXK4HaL0B53Oqc2epzT2nJm6ZLRko7iKrTmeOQ2sjTbgXPAGCIA15asRMTyEgYrNTswufNB0tE4yb0Mi8xivNUaUWqZzfp9JFhnBipI4Dqz0qW13i4LUSgl3FBdOI0OSzgKKNDkp9T2naRzRYnyDyY86k7xMX/G5nT/SqR0vU5GtHPMvuGbeXsSdZnxWk+ZzZ54bPoA06a5z/IWJ4TQER/kOFCKTtjFW6GklNJdX3p5L5l9W6AtBe1KyvJxRwv5ZKfyyp52ysVZaW0hwz79CvoC0RkLP7XcOCAA==

I'll need to investigate if it can be sorted automatically.

**Comment by kkokosa** [comment]
Well, I believe this is requirement on the CIL level, `assembly` must be defined. It is emitted automatically by higher level parsers.

**Comment by am11** [comment]
It was actually a round-trip test on SharpLab: `C# -> IL` then using the generated code, `IL -> JIT ASM`.
Maybe as a "fix", we can just emit a `.assembly SharpLabAssembly { }` in `C#/F#/VB -> IL` case?

**Comment by kkokosa** [comment]
@ashmind after almost a month - do you have any statistics about the IL input popularity? Asking for a friend 😇

**Comment by ashmind** [comment]
Sure -- here are all languages in last 30 days:
image

(might be undercounting for various reasons, e.g. adblockers blocking Azure Insights, but still looks quite good)

**Pull request merged**
